demo/config/routes.rb
Rails.application.routes.draw do
  resources :people

	get "welcome/say_hello" => "welcome#say"
	get "welcome" => "welcome#index"
	root :to => "welcome#index"
	match ':controller(/:action(/:id(.:format)))', :via=> :all
end

demo/app/models/attendee.rb
class Attendee < ActiveRecord::Base
	belongs_to :event # 單數
end

demo/app/models/category.rb
class Category < ActiveRecord::Base
end

demo/app/models/event.rb
class Event < ActiveRecord::Base
	validates_presence_of :name
	has_many :attendees # 複數
	has_one :location # 單數
	has_many :event_groupships
	has_many :groups, :through => :event_groupships
end

demo/app/models/event_groupship.rb
class EventGroupship < ActiveRecord::Base
	belongs_to :event
	belongs_to :group
end

demo/app/models/group.rb
class Group < ActiveRecord::Base
	has_many :event_groupships
	has_many :events, :through => :event_groupships
end

demo/app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :event # 單數
end

demo/app/models/person.rb
class Person < ActiveRecord::Base
end

demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

demo/app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :set_event, :only => [ :show, :edit, :update, :destroy]
	def index
		@events = Event.all
	end
	def new
		@event = Event.new
	end
	def create
		@event = Event.new(event_params)
		@event.save

		redirect_to :action => :index
	end
	def show
		#@event = Event.find(params[:id])
		@page_title = @event.name
	end

	def edit
		#@event = Event.find(params[:id])
	end
	def update
		#@event = Event.find(params[:id])
		@event.update(event_params)

		redirect_to :action => :show, :id => @event
	end
	def destroy
		#@event = Event.find(params[:id])
		@event.destroy

		redirect_to :action => :index
	end

	private

	def event_params
		params.require(:event).permit(:name, :description)
	end

	def set_event
		@event = Event.find(params[:id])
	end
end

demo/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :bio, :birthday)
    end
end

demo/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def say

	end
	def index

	end
end

demo/app/helpers/application_helper.rb
module ApplicationHelper
end

demo/app/helpers/events_helper.rb
module EventsHelper
end

demo/app/helpers/people_helper.rb
module PeopleHelper
end

demo/app/helpers/welcome_helper.rb
module WelcomeHelper
end

demo/app/views/events/edit.erb
<%= form_for @event, :url => { :controller => 'events', :action => 'update', :id => @event } do |f| %>
	<%= f.label :name, "Name" %>
	<%= f.text_field :name %>

	<%= f.label :description, "Description" %>
	<%= f.text_area :description %>

	<%= f.submit "Update" %>
<% end %>

demo/app/views/events/index.html.erb
<ul>
<% @events.each do |event| %>
  <li>
 	  <%= event.name %>
  <%= link_to 'Show', :controller => 'events', :action => 'show', :id => event %>
  <%= link_to 'Edit', :controller => 'events', :action => 'edit', :id => event %>
  <%= link_to 'Delete', :controller => 'events', :action => 'destroy', :id => event %>
  </li>
<% end %>
</ul>
<%= link_to 'New Event', :controller => 'events', :action => 'new' %>

demo/app/views/events/new.html.erb
<%= form_for @event, :url => { :controller => 'events', :action => 'create' } do |f| %>
	<%= f.label :name, "Name" %>
	<%= f.text_field :name %>

	<%= f.label :description, "Description" %>
	<%= f.text_area :description %>

	<%= f.submit "Create" %>
<% end %>

demo/app/views/events/show.html.erb
<%= @event.name %>
<%= simple_format(@event.description) %>

<p><%= link_to 'Back to index', :controller => 'events', :action => 'index' %></p>

demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "Event application" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

demo/app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

demo/app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

demo/app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Birthday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.bio %></td>
        <td><%= person.birthday %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

demo/app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

demo/app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @person.bio %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @person.birthday %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

demo/app/views/welcome/index.html.erb
<p>Hola! It's <%= Time.now %></p>
<p><%= link_to 'Hello!', welcome_say_hello_path %></p>

demo/app/views/welcome/say.html.erb
<h1>Hello, World!</h1>
<p><%= link_to "Home", root_path %></p>